### ISSUE TITLE
Only able to write 20 bytes.

### ISSUE THREAD

**Issue by DonkDH** [chrvadala/node-ble#11]
I'm using a, Raspberry Pi Zero when I try to write a string of 21 characters to a characteristic the application just hangs and hangs the receiving device as well. Where as if I send a string that 20 characters it sends perfectly. 
So the weird thing is that if I use the gatttool console interface I can send significantly longer strings to that same characteristic. 

Any ideas would be much appriciated,
Thanks

**Comment by xalopp** [comment]
Prior to the Raspberry Pi OS based on Debian Bullseye, [BlueZ](http://www.bluez.org) was shipped in version 5.50. This version had a issues when writing a message exceeding the MTU size via D-Bus. GattTool is directly using the Bluetooth stack without D-Bus, that's why this tool worked fine. 

Using the latest Raspberry Pi OS (based on Debian Bullseye) will fix that issue, because BlueZ is shipped with version 5.55 with includes the D-Bus fixes.
